version: "3.12"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python producer.py && python views.py"
